[package]
name = "ras"
version = "0.1.0"
authors = ["Inseok Lee <dlunch@gmail.com>"]
edition = "2018"

[dependencies]
async-std = { version = "^1.9", features = ["attributes", "unstable"] }
futures = { version = "^0.3" }
maplit = { version = "^1.0" }
pretty_env_logger = { version = "^0.4" }
bitflags = { version = "^1.2" }
log = { version = "^0.4" }
multicast-socket = { version = "^0.2" }
hostname = { version = "^0.3" }
get_if_addrs = { version = "^0.5" }
cidr-utils = { version = "^0.5" }
rtp-rs = { version = "^0.6" }